### PR TITLE
[wx] Fix labeling of Show/Hide button in Add/Edit dialog for Alias

### LINKED ISSUE #1178: For an alias, the Show button is not renamed to Hide in the Add/Edit dialog box
When the Add/Edit dialog box for an alias appears and the Show button is clicked to display the password, the button is not renamed to Hide.

### PR DESCRIPTION
**Pull request by rafaelx**
Resolves #1178.

### CODE REVIEW

File: src/ui/wxWidgets/AddEditPropSheetDlg.cpp [hunk 1]
```diff
@@ -1453,6 +1454,7 @@ void AddEditPropSheetDlg::ItemFieldsToPropSheet()
     } else {
       HidePassword();
     }
+    UpdateShowHideButton();
```
Comment (dskrvk) [inline src/ui/wxWidgets/AddEditPropSheetDlg.cpp:1457]: This line is in both if/else branches - maybe move it out?

**Review by dskrvk — APPROVED** [review]
